// frontend/src/app/forms/client-form/client-form.component.ts
import { Component } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';
import { ClientService } from 'src/app/services/client-service';

@Component({
  selector: 'app-client-form',
  templateUrl: './client-form.component.html',
  styleUrls:['./client-form.component.scss']
})
export class ClientFormComponent {
  constructor(private fb:FormBuilder, private api:ClientService) {}
  msg = '';

  statuses = [
    { label: 'PENDING', value: 'PENDING' },
    { label: 'APPROVED', value: 'APPROVED' },
    { label: 'REJECTED', value: 'REJECTED' }
  ];

  form = this.fb.group({
    firstName: ['', Validators.required],
    lastName: ['', Validators.required],
    oib: ['', [Validators.required, Validators.pattern(/\d{11}/)]],
    status: ['PENDING', Validators.required]
  });

  submit() {
    if (this.form.invalid) return;
    this.api.create(this.form.value as any).subscribe({
      next: r => this.msg = `Spremljeno: ${r.firstName} ${r.lastName} (${r.oib})`,
      error: e => this.msg = e?.error?.description ?? 'Greška'
    });
  }
}

<p-card header="Novi klijent" styleClass="p-mb-3">
  <form [formGroup]="form" (ngSubmit)="submit()" class="p-fluid">
    <div class="p-field">
      <label for="firstName">Ime</label>
      <input pInputText id="firstName" formControlName="firstName" />
    </div>
    <div class="p-field">
      <label for="lastName">Prezime</label>
      <input pInputText id="lastName" formControlName="lastName" />
    </div>
    <div class="p-field">
      <label for="oib">OIB</label>
      <input pInputText id="oib" maxlength="11" formControlName="oib" />
    </div>
    <div class="p-field">
      <label for="status">Status</label>
      <p-dropdown id="status"
                  formControlName="status"
                  [options]="statuses"
                  optionLabel="label"
                  optionValue="value"></p-dropdown>
    </div>
    <button pButton type="submit" label="Spremi" [disabled]="form.invalid"></button>
  </form>
  <p style="margin-top:1rem">{{ msg }}</p>
</p-card>

// frontend-react/src/components/ClientForm.tsx
import { useState } from 'react';
import { InputText } from 'primereact/inputtext';
import { Dropdown } from 'primereact/dropdown';
import { Card } from 'primereact/card';
import { Button } from 'primereact/button';
import { createClient, type ClientCreateRequest, type ClientResponse } from '../api';

const statuses = ['PENDING','APPROVED','REJECTED'];

export default function ClientForm() {
  const [form, setForm] = useState<ClientCreateRequest>({ firstName:'', lastName:'', oib:'', status:'PENDING' });
  const [msg, setMsg] = useState('');
  const submit = async () => {
    if (!/^\d{11}$/.test(form.oib) || !form.firstName || !form.lastName) { setMsg('Provjeri polja'); return; }
    try { const r: ClientResponse = await createClient(form); setMsg(`Spremljeno: ${r.firstName} ${r.lastName} (${r.oib})`); }
    catch (e:any) { setMsg(e?.response?.data?.description ?? 'Greška'); }
  };
  return (
    <Card title="Unos klijenta" className="p-mb-3">
      <div className="p-fluid">
        <div className="p-fluid">
        <span className="p-inputgroup p-mb-2"><span className="p-inputgroup-addon">Ime</span>
          <InputText value={form.firstName} onChange={e=>setForm({...form, firstName:e.target.value})}/></span>
        <span className="p-inputgroup p-mb-2"><span className="p-inputgroup-addon">Prezime</span>
          <InputText value={form.lastName} onChange={e=>setForm({...form, lastName:e.target.value})}/></span>
        <span className="p-inputgroup p-mb-2"><span className="p-inputgroup-addon">OIB</span>
          <InputText maxLength={11} value={form.oib} onChange={e=>setForm({...form, oib:e.target.value})}/></span>
        <Dropdown value={form.status} options={statuses} onChange={e=>setForm({...form, status:e.value})} className="p-mb-2"/>
      </div>
        <div className="p-mt-2">
          <Button
            label="Spremi"
            icon="pi pi-save"
            severity="info"
            className="p-button-rounded p-button-raised"
            onClick={submit}
          />
        </div>
      </div>
      <p className="p-mt-2">{msg}</p>
    </Card>
  );
}
